### PR TITLE
move header bar with menu etc to layout file

### LINKED ISSUE #7: move header bar with menu etc to layout file
right now the header bar is a part of the home page_html/home.html.heex

### PR DESCRIPTION
**Pull request by singlefleck**

### CODE REVIEW

**Comment by singlefleck** [comment]
image
@jarlah is this what your expectation? 
added setting and logout inside user_email
let me know if I assumed wrong.

**Comment by jarlah** [comment]
its a nice touch, good work, but i was maybe not clear enough.

i mean moving the menu bar, the complete `<header class="header">` section, from home.html.heex to root.html.heex AND app.html.heex in components/layouts. 

Maybe you can test little bit? the plan is that new pages, like live pages and normal controllers, will have the same top bar? maybe? :) just to make life easier when we start adding actual menu items in the header and want to navigate around.

**Comment by singlefleck** [comment]
ok, got it

**Comment by singlefleck** [comment]
image
I tried to add a header and footer in app.html.heex, but I might have missed a key point regarding how this HTML is rendered via :put_root_layout, :app. 

adding header and footer in both root and app might duplicate twice in a live page or we need to write another router pipeline.

**Comment by jarlah** [comment]
i was probably mistaken :) so its fine to just add it in one of the templates. I was probably not doing any due diligence for the task so i might have pulled some of it from thin air.

**Review by jarlah — CHANGES_REQUESTED** [review]
@singlefleck only some problems with the user menu being a bit difficult

[Screencast from 2024-09-24 15-40-37.webm](https://github.com/user-attachments/assets/1e26d4e3-227d-4b4b-8228-f7e220ac6bc5)

Mouse is not visible, but i try to get the sub menu items into focus, but they keep disappearing 

so maybe look into that menu and we are good.

I see some flickering though, but not sure if thats my browser or tailwind css kicking late ... 

But overall, thanks for the work :partying_face: Nice to collaborate :partying_face:

**Review by jarlah — APPROVED** [review]
Nice work :) Looks better. Now, i will approve, but you want to remove the Go back button and add Itineraries menu item to the top bar we can get a cleaner ui. If not, any of us can do it next in different PR. 

But please use squash if you merge. I dont like several commits into master. PRs thats fine, they can have 100 commits. Master should have one commit per feature or bug introduced/fixed.

**Comment by singlefleck** [comment]
OK, thank you. I will plan a better UI.

**Pull request merged**
